### ISSUE TITLE
Give Credit Where Credit it Due.

### ISSUE THREAD

**Issue by NathanTheBook** [NJayDevelopment/mongoid_forums#5]
All the code from the form-2 project is @mrapple 's. That repo is just a direct copy of his.

**Comment by skipperguy12** [comment]
@NathanTheBook Excuse me, but all credit where due is given. This is not a 'direct copy' of his repo, substantial portions of forem-2 project had their copyright retained in the original file. See here: 2a45af42e2bd341f90ec6a7e6164ceff15b1b64e

Also please read the README.md for a note which states this project is based around his.

Now please, don't make junk issues and accuse me of copying his code. All credit where due is given.

**Comment by skipperguy12** [comment]
@NathanTheBook Also, @mrapple did not make all the code in there. If you look earlier in the history, you will see a mention of a user now deleted who is mentioned on discussions of Mongoid support for forem.
