### ISSUE TITLE
Don't handle issues childishly

### ISSUE THREAD

**Issue by mrapple** [NJayDevelopment/mongoid_forums#7]
Not really an issue as much as a suggestion. I'm referring to #5. Don't do stuff like that, it really makes your project look unprofessional.

**Comment by skipperguy12** [comment]
@mrapple Hi, sorry I didn't do that (another collab). I will edit it all to be blank.

**Comment by mrapple** [comment]
The point is to not edit it to be blank in the first place.

**Comment by skipperguy12** [comment]
@mrapple It was the original editor who changed it. I'm not sure exactly what the original was, but future issues are going to be handled better.

**Comment by mrapple** [comment]
Fair enough, just leave the comments though next time I would say. Then again, it's up to you. Not my project.

**Comment by MasterEjay** [comment]
Also, in terms of credit, its been given: 

> See here for the public version this project is based on (and borrows some code from): https://github.com/kultus/forem-2

**Comment by mrapple** [comment]
I'm aware it has been given and the respective files contain the proper copyright notice, thanks.
